// // data.tsx
// export interface Employee {
//   id: number;
//   firstName: string;
//   lastName: string;
//   startDate: string;
//   departments: string;
//   dateOfBirth: string;
//   street: string;
//   city: string;
//   stateCountry: string;
//   zipCode: string;
// }

// export const employeesData: Employee[] = [
//   {
//     id: 1,
//     firstName: "Jammie",
//     lastName: "Eusden",
//     startDate: "2019-03-06",
//     departments: "YE-AD",
//     dateOfBirth: "1992-11-28",
//     street: "813 Cody Center",
//     city: "Sioux City",
//     stateCountry: "Iowa",
//     zipCode: "51105",
//   },
//   {
//     id: 2,
//     firstName: "Katheryn",
//     lastName: "Corish",
//     startDate: "2020-10-30",
//     departments: "US-WY",
//     dateOfBirth: "1980-07-05",
//     street: "161 Main Point",
//     city: "Anaheim",
//     stateCountry: "California",
//     zipCode: "92805",
//   },
//   {
//     id: 3,
//     firstName: "Tore",
//     lastName: "Moggan",
//     startDate: "2021-06-03",
//     departments: "ES-CN",
//     dateOfBirth: "1998-07-22",
//     street: "870 John Wall Hill",
//     city: "Denver",
//     stateCountry: "Colorado",
//     zipCode: "80204",
//   },
//   {
//     id: 4,
//     firstName: "Rochette",
//     lastName: "Kochs",
//     startDate: "2018-12-06",
//     departments: "BZ-CY",
//     dateOfBirth: "1987-09-22",
//     street: "6 Melody Parkway",
//     city: "Knoxville",
//     stateCountry: "Tennessee",
//     zipCode: "37939",
//   },
//   {
//     id: 5,
//     firstName: "Herby",
//     lastName: "Malafe",
//     startDate: "2022-09-27",
//     departments: "US-WI",
//     dateOfBirth: "1994-09-20",
//     street: "94 Hoard Center",
//     city: "Phoenix",
//     stateCountry: "Arizona",
//     zipCode: "85072",
//   },
//   {
//     id: 6,
//     firstName: "Beverlie",
//     lastName: "Sillis",
//     startDate: "2019-01-23",
//     departments: "US-OR",
//     dateOfBirth: "1977-07-10",
//     street: "1 Susan Street",
//     city: "Philadelphia",
//     stateCountry: "Pennsylvania",
//     zipCode: "19172",
//   },
//   {
//     id: 7,
//     firstName: "Eve",
//     lastName: "Sagrott",
//     startDate: "2023-09-02",
//     departments: "PG-WBK",
//     dateOfBirth: "1980-10-05",
//     street: "589 Oxford Street",
//     city: "Nashville",
//     stateCountry: "Tennessee",
//     zipCode: "37245",
//   },
//   {
//     id: 8,
//     firstName: "Teodora",
//     lastName: "Burchfield",
//     startDate: "2020-01-24",
//     departments: "CN-43",
//     dateOfBirth: "1987-07-04",
//     street: "382 Memorial Pass",
//     city: "Milwaukee",
//     stateCountry: "Wisconsin",
//     zipCode: "53210",
//   },
//   {
//     id: 9,
//     firstName: "Leo",
//     lastName: "Billows",
//     startDate: "2022-01-04",
//     departments: "BO-P",
//     dateOfBirth: "1989-04-28",
//     street: "9 Loeprich Center",
//     city: "Pensacola",
//     stateCountry: "Florida",
//     zipCode: "32505",
//   },
//   {
//     id: 10,
//     firstName: "Ivett",
//     lastName: "Van den Velde",
//     startDate: "2022-12-15",
//     departments: "MX-SON",
//     dateOfBirth: "1998-09-06",
//     street: "51 Namekagon Drive",
//     city: "Pasadena",
//     stateCountry: "California",
//     zipCode: "91131",
//   },
//   {
//     id: 11,
//     firstName: "Sal",
//     lastName: "Kelston",
//     startDate: "2019-11-05",
//     departments: "CO-SUC",
//     dateOfBirth: "1989-04-07",
//     street: "7205 Laurel Plaza",
//     city: "Birmingham",
//     stateCountry: "Alabama",
//     zipCode: "35210",
//   },
//   {
//     id: 12,
//     firstName: "Pegeen",
//     lastName: "Felix",
//     startDate: "2023-01-02",
//     departments: "ET-OR",
//     dateOfBirth: "1985-10-24",
//     street: "176 Banding Crossing",
//     city: "New York City",
//     stateCountry: "New York",
//     zipCode: "10024",
//   },
//   {
//     id: 13,
//     firstName: "Lenora",
//     lastName: "Beedham",
//     startDate: "2018-06-22",
//     departments: "KE-700",
//     dateOfBirth: "1989-11-10",
//     street: "04444 Di Loreto Plaza",
//     city: "San Bernardino",
//     stateCountry: "California",
//     zipCode: "92405",
//   },
//   {
//     id: 14,
//     firstName: "Arly",
//     lastName: "Matiashvili",
//     startDate: "2018-09-03",
//     departments: "FR-U",
//     dateOfBirth: "1990-02-19",
//     street: "1 Commercial Court",
//     city: "Dallas",
//     stateCountry: "Texas",
//     zipCode: "75353",
//   },
//   {
//     id: 15,
//     firstName: "Lamar",
//     lastName: "McKean",
//     startDate: "2019-05-19",
//     departments: "US-AK",
//     dateOfBirth: "1994-10-06",
//     street: "7 Mendota Park",
//     city: "Fort Wayne",
//     stateCountry: "Indiana",
//     zipCode: "46825",
//   },
//   {
//     id: 16,
//     firstName: "Donia",
//     lastName: "Crowder",
//     startDate: "2022-01-22",
//     departments: "US-MA",
//     dateOfBirth: "1986-03-20",
//     street: "16985 Old Gate Center",
//     city: "Colorado Springs",
//     stateCountry: "Colorado",
//     zipCode: "80905",
//   },
//   {
//     id: 17,
//     firstName: "Arlyn",
//     lastName: "Pedel",
//     startDate: "2019-08-02",
//     departments: "GT-PE",
//     dateOfBirth: "1988-08-07",
//     street: "4 Lunder Place",
//     city: "Buffalo",
//     stateCountry: "New York",
//     zipCode: "14263",
//   },
//   {
//     id: 18,
//     firstName: "Angelle",
//     lastName: "Seifenmacher",
//     startDate: "2021-12-09",
//     departments: "CM-SW",
//     dateOfBirth: "1983-01-18",
//     street: "5 Homewood Road",
//     city: "Loretto",
//     stateCountry: "Minnesota",
//     zipCode: "55598",
//   },
//   {
//     id: 19,
//     firstName: "Mora",
//     lastName: "Bastiman",
//     startDate: "2018-09-23",
//     departments: "SO-GE",
//     dateOfBirth: "1982-02-23",
//     street: "67 Merry Pass",
//     city: "Lake Charles",
//     stateCountry: "Louisiana",
//     zipCode: "70607",
//   },
//   {
//     id: 20,
//     firstName: "Tara",
//     lastName: "Zecchii",
//     startDate: "2020-06-10",
//     departments: "ZA-EC",
//     dateOfBirth: "1987-04-29",
//     street: "41682 Tennyson Road",
//     city: "New York City",
//     stateCountry: "New York",
//     zipCode: "10203",
//   },
//   {
//     id: 21,
//     firstName: "Dominique",
//     lastName: "Keers",
//     startDate: "2018-04-06",
//     departments: "AR-Q",
//     dateOfBirth: "1988-03-25",
//     street: "025 Loeprich Lane",
//     city: "Seattle",
//     stateCountry: "Washington",
//     zipCode: "98121",
//   },
//   {
//     id: 22,
//     firstName: "Carri",
//     lastName: "Stritton",
//     startDate: "2020-07-20",
//     departments: "AU-NT",
//     dateOfBirth: "1993-10-05",
//     street: "96 Iowa Avenue",
//     city: "Fullerton",
//     stateCountry: "California",
//     zipCode: "92835",
//   },
//   {
//     id: 23,
//     firstName: "Korey",
//     lastName: "Duce",
//     startDate: "2018-09-28",
//     departments: "ID-NB",
//     dateOfBirth: "1986-07-09",
//     street: "09100 Lillian Road",
//     city: "Boston",
//     stateCountry: "Massachusetts",
//     zipCode: "02109",
//   },
//   {
//     id: 24,
//     firstName: "Karole",
//     lastName: "Pitkins",
//     startDate: "2022-03-07",
//     departments: "GB-ENG",
//     dateOfBirth: "1984-06-11",
//     street: "7741 Twin Pines Junction",
//     city: "Gatesville",
//     stateCountry: "Texas",
//     zipCode: "76598",
//   },
//   {
//     id: 25,
//     firstName: "Yankee",
//     lastName: "MacDwyer",
//     startDate: "2023-05-30",
//     departments: "BR-MS",
//     dateOfBirth: "1985-06-30",
//     street: "6 Roth Drive",
//     city: "Orlando",
//     stateCountry: "Florida",
//     zipCode: "32819",
//   },
//   {
//     id: 26,
//     firstName: "Stavros",
//     lastName: "Sargeant",
//     startDate: "2021-11-22",
//     departments: "ID-MU",
//     dateOfBirth: "1986-10-31",
//     street: "5550 Butterfield Plaza",
//     city: "Miami",
//     stateCountry: "Florida",
//     zipCode: "33153",
//   },
//   {
//     id: 27,
//     firstName: "Colette",
//     lastName: "Gales",
//     startDate: "2019-12-18",
//     departments: "NZ-CAN",
//     dateOfBirth: "1998-12-01",
//     street: "391 Dorton Plaza",
//     city: "Anaheim",
//     stateCountry: "California",
//     zipCode: "92825",
//   },
//   {
//     id: 28,
//     firstName: "Paquito",
//     lastName: "Crinkley",
//     startDate: "2018-07-30",
//     departments: "CO-TOL",
//     dateOfBirth: "1979-12-29",
//     street: "37758 Canary Crossing",
//     city: "Ann Arbor",
//     stateCountry: "Michigan",
//     zipCode: "48107",
//   },
//   {
//     id: 29,
//     firstName: "Shalne",
//     lastName: "Fakeley",
//     startDate: "2019-05-26",
//     departments: "US-NY",
//     dateOfBirth: "1984-04-26",
//     street: "9525 Warbler Court",
//     city: "Jersey City",
//     stateCountry: "New Jersey",
//     zipCode: "07305",
//   },
//   {
//     id: 30,
//     firstName: "Ardenia",
//     lastName: "Harry",
//     startDate: "2020-08-28",
//     departments: "AU-NT",
//     dateOfBirth: "1990-03-25",
//     street: "12 Melody Street",
//     city: "Arvada",
//     stateCountry: "Colorado",
//     zipCode: "80005",
//   },
//   {
//     id: 31,
//     firstName: "Kendrick",
//     lastName: "Cadwallader",
//     startDate: "2023-01-21",
//     departments: "EC-S",
//     dateOfBirth: "1995-08-20",
//     street: "2 Kedzie Street",
//     city: "Birmingham",
//     stateCountry: "Alabama",
//     zipCode: "35295",
//   },
//   {
//     id: 32,
//     firstName: "Georg",
//     lastName: "Mithan",
//     startDate: "2019-09-16",
//     departments: "AE-AZ",
//     dateOfBirth: "1990-01-30",
//     street: "7953 Westridge Road",
//     city: "Jamaica",
//     stateCountry: "New York",
//     zipCode: "11436",
//   },
//   {
//     id: 33,
//     firstName: "Sharl",
//     lastName: "Catterell",
//     startDate: "2018-05-11",
//     departments: "ID-SU",
//     dateOfBirth: "1992-12-22",
//     street: "29937 Independence Crossing",
//     city: "Austin",
//     stateCountry: "Texas",
//     zipCode: "78726",
//   },
//   {
//     id: 34,
//     firstName: "Rosalia",
//     lastName: "Rolinson",
//     startDate: "2018-07-24",
//     departments: "CA-BC",
//     dateOfBirth: "1981-06-01",
//     street: "1 Helena Lane",
//     city: "Lansing",
//     stateCountry: "Michigan",
//     zipCode: "48930",
//   },
//   {
//     id: 35,
//     firstName: "Brunhilde",
//     lastName: "Olivari",
//     startDate: "2023-05-23",
//     departments: "IS-7",
//     dateOfBirth: "1977-05-20",
//     street: "35 Farmco Park",
//     city: "Fayetteville",
//     stateCountry: "North Carolina",
//     zipCode: "28314",
//   },
//   {
//     id: 36,
//     firstName: "Zia",
//     lastName: "Fullman",
//     startDate: "2022-09-20",
//     departments: "SB-WE",
//     dateOfBirth: "1980-04-26",
//     street: "79 Menomonie Road",
//     city: "Fresno",
//     stateCountry: "California",
//     zipCode: "93726",
//   },
//   {
//     id: 37,
//     firstName: "Bat",
//     lastName: "Jeacock",
//     startDate: "2020-08-05",
//     departments: "US-WA",
//     dateOfBirth: "1985-05-15",
//     street: "38 Mayer Road",
//     city: "Baton Rouge",
//     stateCountry: "Louisiana",
//     zipCode: "70883",
//   },
//   {
//     id: 38,
//     firstName: "Lauretta",
//     lastName: "McKechnie",
//     startDate: "2018-11-15",
//     departments: "US-CA",
//     dateOfBirth: "1989-08-30",
//     street: "7587 Pleasure Drive",
//     city: "Round Rock",
//     stateCountry: "Texas",
//     zipCode: "78682",
//   },
//   {
//     id: 39,
//     firstName: "Paco",
//     lastName: "Auchterlonie",
//     startDate: "2021-06-09",
//     departments: "US-MA",
//     dateOfBirth: "1992-02-07",
//     street: "2769 Dunning Way",
//     city: "Dallas",
//     stateCountry: "Texas",
//     zipCode: "75397",
//   },
//   {
//     id: 40,
//     firstName: "Kendre",
//     lastName: "Dommett",
//     startDate: "2023-08-13",
//     departments: "IS-4",
//     dateOfBirth: "1992-11-17",
//     street: "86 Oriole Way",
//     city: "Houston",
//     stateCountry: "Texas",
//     zipCode: "77212",
//   },
//   {
//     id: 41,
//     firstName: "Chiquita",
//     lastName: "Moniker",
//     startDate: "2022-01-27",
//     departments: "EC-G",
//     dateOfBirth: "1987-12-10",
//     street: "1554 Buell Pass",
//     city: "Seattle",
//     stateCountry: "Washington",
//     zipCode: "98195",
//   },
//   {
//     id: 42,
//     firstName: "Claudetta",
//     lastName: "Boswood",
//     startDate: "2021-03-31",
//     departments: "US-CA",
//     dateOfBirth: "1981-04-04",
//     street: "11091 Mandrake Center",
//     city: "El Paso",
//     stateCountry: "Texas",
//     zipCode: "79994",
//   },
//   {
//     id: 43,
//     firstName: "Brantley",
//     lastName: "Kaesmans",
//     startDate: "2022-02-13",
//     departments: "ZA-EC",
//     dateOfBirth: "1989-07-26",
//     street: "03 Pleasure Plaza",
//     city: "Lubbock",
//     stateCountry: "Texas",
//     zipCode: "79405",
//   },
//   {
//     id: 44,
//     firstName: "Evangeline",
//     lastName: "Whapple",
//     startDate: "2020-06-25",
//     departments: "CN-61",
//     dateOfBirth: "1979-12-02",
//     street: "07 Annamark Court",
//     city: "Pensacola",
//     stateCountry: "Florida",
//     zipCode: "32511",
//   },
//   {
//     id: 45,
//     firstName: "Michal",
//     lastName: "Poynzer",
//     startDate: "2018-02-07",
//     departments: "AR-X",
//     dateOfBirth: "1983-03-31",
//     street: "211 Birchwood Junction",
//     city: "New Orleans",
//     stateCountry: "Louisiana",
//     zipCode: "70165",
//   },
//   {
//     id: 46,
//     firstName: "Olenolin",
//     lastName: "Oselton",
//     startDate: "2021-09-10",
//     departments: "ZA-GT",
//     dateOfBirth: "1983-06-05",
//     street: "9850 Kropf Circle",
//     city: "Baltimore",
//     stateCountry: "Maryland",
//     zipCode: "21275",
//   },
//   {
//     id: 47,
//     firstName: "Glori",
//     lastName: "Waliszewski",
//     startDate: "2019-01-12",
//     departments: "IE-G",
//     dateOfBirth: "1995-09-15",
//     street: "62 Fairview Hill",
//     city: "Baltimore",
//     stateCountry: "Maryland",
//     zipCode: "21216",
//   },
//   {
//     id: 48,
//     firstName: "Alysa",
//     lastName: "MacDunleavy",
//     startDate: "2020-09-25",
//     departments: "IN-GJ",
//     dateOfBirth: "1994-08-20",
//     street: "51 Randy Avenue",
//     city: "Washington",
//     stateCountry: "District of Columbia",
//     zipCode: "20442",
//   },
//   {
//     id: 49,
//     firstName: "Bord",
//     lastName: "Healeas",
//     startDate: "2021-05-03",
//     departments: "ID-MU",
//     dateOfBirth: "1993-04-17",
//     street: "6 Roth Alley",
//     city: "Fort Worth",
//     stateCountry: "Texas",
//     zipCode: "76105",
//   },
//   {
//     id: 50,
//     firstName: "Bendicty",
//     lastName: "Morrowe",
//     startDate: "2018-05-16",
//     departments: "GR-22",
//     dateOfBirth: "1983-07-03",
//     street: "0 Meadow Vale Pass",
//     city: "Montgomery",
//     stateCountry: "Alabama",
//     zipCode: "36125",
//   },
//   {
//     id: 51,
//     firstName: "Kizzie",
//     lastName: "Seabon",
//     startDate: "2022-07-16",
//     departments: "AU-QLD",
//     dateOfBirth: "1987-12-25",
//     street: "293 Magdeline Center",
//     city: "Jeffersonville",
//     stateCountry: "Indiana",
//     zipCode: "47134",
//   },
//   {
//     id: 52,
//     firstName: "Filmore",
//     lastName: "Toderini",
//     startDate: "2018-08-30",
//     departments: "AU-WA",
//     dateOfBirth: "1982-08-05",
//     street: "6501 Kim Trail",
//     city: "Cincinnati",
//     stateCountry: "Ohio",
//     zipCode: "45223",
//   },
//   {
//     id: 53,
//     firstName: "Belia",
//     lastName: "Sommerled",
//     startDate: "2021-08-05",
//     departments: "AU-SA",
//     dateOfBirth: "1980-03-12",
//     street: "9454 Holmberg Crossing",
//     city: "Phoenix",
//     stateCountry: "Arizona",
//     zipCode: "85072",
//   },
//   {
//     id: 54,
//     firstName: "Deane",
//     lastName: "Larret",
//     startDate: "2021-10-21",
//     departments: "PG-ESW",
//     dateOfBirth: "1992-03-22",
//     street: "49 Schlimgen Trail",
//     city: "Hialeah",
//     stateCountry: "Florida",
//     zipCode: "33018",
//   },
//   {
//     id: 55,
//     firstName: "Benedikt",
//     lastName: "Maes",
//     startDate: "2023-11-21",
//     departments: "US-AK",
//     dateOfBirth: "1993-01-27",
//     street: "8 2nd Place",
//     city: "Newton",
//     stateCountry: "Massachusetts",
//     zipCode: "02162",
//   },
//   {
//     id: 56,
//     firstName: "Harlan",
//     lastName: "Saintsbury",
//     startDate: "2021-12-27",
//     departments: "CA-SK",
//     dateOfBirth: "1985-03-05",
//     street: "992 Bartillon Pass",
//     city: "Charlotte",
//     stateCountry: "North Carolina",
//     zipCode: "28225",
//   },
//   {
//     id: 57,
//     firstName: "Odelinda",
//     lastName: "Blose",
//     startDate: "2018-01-07",
//     departments: "CI-01",
//     dateOfBirth: "1987-08-06",
//     street: "55849 Nancy Court",
//     city: "Carson City",
//     stateCountry: "Nevada",
//     zipCode: "89706",
//   },
//   {
//     id: 58,
//     firstName: "Coleen",
//     lastName: "Haughin",
//     startDate: "2022-03-23",
//     departments: "DZ-09",
//     dateOfBirth: "1995-02-10",
//     street: "32 Harper Terrace",
//     city: "Sparks",
//     stateCountry: "Nevada",
//     zipCode: "89436",
//   },
//   {
//     id: 59,
//     firstName: "Noel",
//     lastName: "Bretelle",
//     startDate: "2023-07-13",
//     departments: "US-MN",
//     dateOfBirth: "1990-08-15",
//     street: "44 Hermina Alley",
//     city: "Detroit",
//     stateCountry: "Michigan",
//     zipCode: "48232",
//   },
//   {
//     id: 60,
//     firstName: "Sig",
//     lastName: "Joslow",
//     startDate: "2022-08-11",
//     departments: "US-PA",
//     dateOfBirth: "1993-09-14",
//     street: "5 Stuart Court",
//     city: "Washington",
//     stateCountry: "District of Columbia",
//     zipCode: "20319",
//   },
//   {
//     id: 61,
//     firstName: "Erinna",
//     lastName: "Lippett",
//     startDate: "2019-11-03",
//     departments: "KY-U-A",
//     dateOfBirth: "1992-02-20",
//     street: "9 Linden Center",
//     city: "Naperville",
//     stateCountry: "Illinois",
//     zipCode: "60567",
//   },
//   {
//     id: 62,
//     firstName: "Clarke",
//     lastName: "Kirsche",
//     startDate: "2021-04-11",
//     departments: "IL-HA",
//     dateOfBirth: "1997-09-14",
//     street: "60562 Porter Road",
//     city: "Orlando",
//     stateCountry: "Florida",
//     zipCode: "32859",
//   },
//   {
//     id: 63,
//     firstName: "Krista",
//     lastName: "Vallens",
//     startDate: "2021-09-22",
//     departments: "US-TN",
//     dateOfBirth: "1978-08-26",
//     street: "50 Dexter Crossing",
//     city: "Bloomington",
//     stateCountry: "Indiana",
//     zipCode: "47405",
//   },
//   {
//     id: 64,
//     firstName: "Brooks",
//     lastName: "Claesens",
//     startDate: "2019-08-04",
//     departments: "ZM-01",
//     dateOfBirth: "1993-10-03",
//     street: "909 Bellgrove Circle",
//     city: "Waterloo",
//     stateCountry: "Iowa",
//     zipCode: "50706",
//   },
//   {
//     id: 65,
//     firstName: "Celia",
//     lastName: "Suthworth",
//     startDate: "2023-02-25",
//     departments: "FR-S",
//     dateOfBirth: "1979-03-20",
//     street: "1772 Express Circle",
//     city: "Washington",
//     stateCountry: "District of Columbia",
//     zipCode: "20016",
//   },
//   {
//     id: 66,
//     firstName: "Erminie",
//     lastName: "Towriss",
//     startDate: "2020-10-02",
//     departments: "PE-MDD",
//     dateOfBirth: "1997-01-21",
//     street: "61132 Independence Crossing",
//     city: "Oklahoma City",
//     stateCountry: "Oklahoma",
//     zipCode: "73179",
//   },
//   {
//     id: 67,
//     firstName: "Basia",
//     lastName: "Bromwich",
//     startDate: "2021-03-23",
//     departments: "NP-NA",
//     dateOfBirth: "1992-10-24",
//     street: "71 Shasta Alley",
//     city: "Memphis",
//     stateCountry: "Tennessee",
//     zipCode: "38119",
//   },
//   {
//     id: 68,
//     firstName: "Marsha",
//     lastName: "Hutchcraft",
//     startDate: "2020-07-08",
//     departments: "PG-ESW",
//     dateOfBirth: "1985-01-14",
//     street: "74773 Bartelt Parkway",
//     city: "Saint Paul",
//     stateCountry: "Minnesota",
//     zipCode: "55108",
//   },
//   {
//     id: 69,
//     firstName: "Rawley",
//     lastName: "Common",
//     startDate: "2020-07-15",
//     departments: "CL-CO",
//     dateOfBirth: "1985-12-31",
//     street: "2217 Cambridge Court",
//     city: "Ogden",
//     stateCountry: "Utah",
//     zipCode: "84403",
//   },
//   {
//     id: 70,
//     firstName: "Galvan",
//     lastName: "Collington",
//     startDate: "2021-05-07",
//     departments: "GL-U-A",
//     dateOfBirth: "1996-02-21",
//     street: "71 Morrow Trail",
//     city: "Great Neck",
//     stateCountry: "New York",
//     zipCode: "11024",
//   },
//   {
//     id: 71,
//     firstName: "Myrilla",
//     lastName: "Doggart",
//     startDate: "2018-08-25",
//     departments: "US-CA",
//     dateOfBirth: "1984-05-03",
//     street: "36006 Clemons Plaza",
//     city: "Boise",
//     stateCountry: "Idaho",
//     zipCode: "83711",
//   },
//   {
//     id: 72,
//     firstName: "Darcee",
//     lastName: "Collocott",
//     startDate: "2020-07-11",
//     departments: "NZ-CAN",
//     dateOfBirth: "1993-12-28",
//     street: "21 Reindahl Pass",
//     city: "Kansas City",
//     stateCountry: "Missouri",
//     zipCode: "64149",
//   },
//   {
//     id: 73,
//     firstName: "Cordey",
//     lastName: "Rosendale",
//     startDate: "2021-11-23",
//     departments: "ZM-03",
//     dateOfBirth: "1979-12-01",
//     street: "94053 Fordem Junction",
//     city: "Dallas",
//     stateCountry: "Texas",
//     zipCode: "75277",
//   },
//   {
//     id: 74,
//     firstName: "Markos",
//     lastName: "Brightie",
//     startDate: "2021-04-25",
//     departments: "AR-A",
//     dateOfBirth: "1978-03-10",
//     street: "52461 Prairieview Place",
//     city: "Amarillo",
//     stateCountry: "Texas",
//     zipCode: "79116",
//   },
//   {
//     id: 75,
//     firstName: "Jessamine",
//     lastName: "Blackeby",
//     startDate: "2022-06-05",
//     departments: "US-WY",
//     dateOfBirth: "1987-11-01",
//     street: "85 Pawling Pass",
//     city: "Scottsdale",
//     stateCountry: "Arizona",
//     zipCode: "85271",
//   },
//   {
//     id: 76,
//     firstName: "Malina",
//     lastName: "Wilkes",
//     startDate: "2023-01-27",
//     departments: "JP-46",
//     dateOfBirth: "1998-05-12",
//     street: "8838 Mosinee Trail",
//     city: "Salem",
//     stateCountry: "Oregon",
//     zipCode: "97312",
//   },
//   {
//     id: 77,
//     firstName: "Sylvan",
//     lastName: "Dalgardno",
//     startDate: "2020-05-03",
//     departments: "BR-SP",
//     dateOfBirth: "1983-08-12",
//     street: "6 North Trail",
//     city: "Los Angeles",
//     stateCountry: "California",
//     zipCode: "90020",
//   },
//   {
//     id: 78,
//     firstName: "Salem",
//     lastName: "Moreno",
//     startDate: "2023-10-06",
//     departments: "BR-SP",
//     dateOfBirth: "1998-04-14",
//     street: "67 Pawling Trail",
//     city: "Jacksonville",
//     stateCountry: "Florida",
//     zipCode: "32244",
//   },
//   {
//     id: 79,
//     firstName: "Hephzibah",
//     lastName: "Rillett",
//     startDate: "2023-11-20",
//     departments: "ID-JK",
//     dateOfBirth: "1985-12-18",
//     street: "26630 Chinook Plaza",
//     city: "Boise",
//     stateCountry: "Idaho",
//     zipCode: "83722",
//   },
//   {
//     id: 80,
//     firstName: "Zena",
//     lastName: "Ebourne",
//     startDate: "2022-12-28",
//     departments: "NZ-TKI",
//     dateOfBirth: "1985-05-04",
//     street: "780 Upham Hill",
//     city: "Seattle",
//     stateCountry: "Washington",
//     zipCode: "98166",
//   },
//   {
//     id: 81,
//     firstName: "Cosmo",
//     lastName: "Daice",
//     startDate: "2020-12-18",
//     departments: "ID-ST",
//     dateOfBirth: "1987-12-22",
//     street: "46 Basil Crossing",
//     city: "Lafayette",
//     stateCountry: "Louisiana",
//     zipCode: "70505",
//   },
//   {
//     id: 82,
//     firstName: "Elisabet",
//     lastName: "Fannin",
//     startDate: "2022-12-05",
//     departments: "US-AK",
//     dateOfBirth: "1981-11-19",
//     street: "0 Ruskin Street",
//     city: "Mobile",
//     stateCountry: "Alabama",
//     zipCode: "36670",
//   },
//   {
//     id: 83,
//     firstName: "Gasparo",
//     lastName: "McRamsey",
//     startDate: "2021-03-13",
//     departments: "AU-QLD",
//     dateOfBirth: "1977-08-05",
//     street: "14269 Debs Lane",
//     city: "Young America",
//     stateCountry: "Minnesota",
//     zipCode: "55551",
//   },
//   {
//     id: 84,
//     firstName: "Pia",
//     lastName: "Berrey",
//     startDate: "2022-04-09",
//     departments: "PF-U-A",
//     dateOfBirth: "1988-04-14",
//     street: "87959 Fairview Place",
//     city: "Springfield",
//     stateCountry: "Illinois",
//     zipCode: "62794",
//   },
//   {
//     id: 85,
//     firstName: "Hall",
//     lastName: "Haddy",
//     startDate: "2023-05-15",
//     departments: "BZ-BZ",
//     dateOfBirth: "1983-02-04",
//     street: "09249 4th Avenue",
//     city: "Santa Monica",
//     stateCountry: "California",
//     zipCode: "90405",
//   },
//   {
//     id: 86,
//     firstName: "Deana",
//     lastName: "Rosebotham",
//     startDate: "2019-08-17",
//     departments: "JP-47",
//     dateOfBirth: "1993-12-16",
//     street: "2 Mariners Cove Court",
//     city: "Saint Petersburg",
//     stateCountry: "Florida",
//     zipCode: "33742",
//   },
//   {
//     id: 87,
//     firstName: "Fancie",
//     lastName: "Halson",
//     startDate: "2021-07-20",
//     departments: "ZW-MV",
//     dateOfBirth: "1979-11-12",
//     street: "4974 Forest Dale Lane",
//     city: "Atlanta",
//     stateCountry: "Georgia",
//     zipCode: "30311",
//   },
//   {
//     id: 88,
//     firstName: "Alis",
//     lastName: "Gilfillan",
//     startDate: "2021-07-08",
//     departments: "PH-PLW",
//     dateOfBirth: "1979-05-25",
//     street: "00 Clemons Park",
//     city: "Atlanta",
//     stateCountry: "Georgia",
//     zipCode: "31136",
//   },
//   {
//     id: 89,
//     firstName: "Eve",
//     lastName: "Orys",
//     startDate: "2022-08-20",
//     departments: "SE-BD",
//     dateOfBirth: "1987-02-19",
//     street: "717 Talisman Drive",
//     city: "Albuquerque",
//     stateCountry: "New Mexico",
//     zipCode: "87105",
//   },
//   {
//     id: 90,
//     firstName: "Filberte",
//     lastName: "Tiffney",
//     startDate: "2019-04-16",
//     departments: "MA-BAH",
//     dateOfBirth: "1992-02-15",
//     street: "0 Eagle Crest Plaza",
//     city: "Harrisburg",
//     stateCountry: "Pennsylvania",
//     zipCode: "17110",
//   },
//   {
//     id: 91,
//     firstName: "Mahalia",
//     lastName: "Goff",
//     startDate: "2018-02-23",
//     departments: "PF-U-A",
//     dateOfBirth: "1988-08-07",
//     street: "10179 Longview Circle",
//     city: "Saint Louis",
//     stateCountry: "Missouri",
//     zipCode: "63169",
//   },
//   {
//     id: 92,
//     firstName: "Amery",
//     lastName: "Gething",
//     startDate: "2020-03-16",
//     departments: "KE-110",
//     dateOfBirth: "1983-05-20",
//     street: "17222 Stoughton Crossing",
//     city: "Pensacola",
//     stateCountry: "Florida",
//     zipCode: "32505",
//   },
//   {
//     id: 93,
//     firstName: "Marcelline",
//     lastName: "de Mullett",
//     startDate: "2022-09-07",
//     departments: "CN-53",
//     dateOfBirth: "1983-04-22",
//     street: "0983 Veith Hill",
//     city: "Sarasota",
//     stateCountry: "Florida",
//     zipCode: "34276",
//   },
//   {
//     id: 94,
//     firstName: "Manuel",
//     lastName: "Ephson",
//     startDate: "2020-06-15",
//     departments: "BR-MT",
//     dateOfBirth: "1987-01-29",
//     street: "25 School Drive",
//     city: "Sacramento",
//     stateCountry: "California",
//     zipCode: "94286",
//   },
//   {
//     id: 95,
//     firstName: "Georgeta",
//     lastName: "Leele",
//     startDate: "2023-07-17",
//     departments: "US-LA",
//     dateOfBirth: "1996-08-23",
//     street: "6207 Anthes Road",
//     city: "Reno",
//     stateCountry: "Nevada",
//     zipCode: "89505",
//   },
//   {
//     id: 96,
//     firstName: "Norrie",
//     lastName: "Cabrales",
//     startDate: "2018-10-28",
//     departments: "US-WY",
//     dateOfBirth: "1985-10-12",
//     street: "97056 Meadow Ridge Crossing",
//     city: "Falls Church",
//     stateCountry: "Virginia",
//     zipCode: "22047",
//   },
//   {
//     id: 97,
//     firstName: "Waite",
//     lastName: "Busch",
//     startDate: "2021-09-15",
//     departments: "CN-50",
//     dateOfBirth: "1996-01-08",
//     street: "440 Springs Drive",
//     city: "Rochester",
//     stateCountry: "New York",
//     zipCode: "14619",
//   },
//   {
//     id: 98,
//     firstName: "Lucila",
//     lastName: "Panons",
//     startDate: "2022-12-31",
//     departments: "VN-23",
//     dateOfBirth: "1988-11-22",
//     street: "6 Clyde Gallagher Road",
//     city: "Dallas",
//     stateCountry: "Texas",
//     zipCode: "75210",
//   },
//   {
//     id: 99,
//     firstName: "Benedicta",
//     lastName: "Gillogley",
//     startDate: "2022-07-31",
//     departments: "PH-LAS",
//     dateOfBirth: "1995-01-12",
//     street: "951 Summer Ridge Park",
//     city: "Juneau",
//     stateCountry: "Alaska",
//     zipCode: "99812",
//   },
//   {
//     id: 100,
//     firstName: "Cathleen",
//     lastName: "Crosskill",
//     startDate: "2023-11-05",
//     departments: "KH-2",
//     dateOfBirth: "1995-10-02",
//     street: "88 Longview Avenue",
//     city: "Oakland",
//     stateCountry: "California",
//     zipCode: "94605",
//   },
// ];

// export default employeesData;
